const ArticlesData = [
  {
    image: "/icons/article1.png",
    title: "7 Rules of Effective Branding",
    description: "Why Branding matters for your Business",
    chips: ["Branding", "Communication", "Branding"],
    category: "business",
    label: "created",
    author: "Maria Doe",
    time: "20 Sep 2022",
  },
  {
    image: "/icons/economy.png",
    title: "Research on biodiversity an environment",
    description: "Lorem ipsum dolor sit amet, consectetur",
    chips: ["World", "Population"],
    category: "economy",
    label: "published",
    author: "Maria Doe",
    time: "20 Sep 2022",
  },
  {
    image: "/icons/politics.png",
    title: "Close and historical ties to the government",
    description: "Lorem ipsum dolor sit amet, consectetur",
    chips: ["Politics", "Defense"],
    category: "politics",
    label: "published",
    author: "Maria Doe",
    time: "20 Sep 2022",
  },
  {
    image: "/icons/article1.png",
    title: "7 Rules of Effective Branding",
    description: "Why Branding matters for your Business",
    chips: ["Branding", "Communication", "Branding"],
    category: "business",
    label: "created",
    author: "Maria Doe",
    time: "20 Sep 2022",
  },
  {
    image: "/icons/economy.png",
    title: "Research on biodiversity an ",
    description: "Lorem ipsum dolor sit amet, consectetur",
    chips: ["World", "Population"],
    category: "economy",
    label: "published",
    author: "Maria Doe",
    time: "20 Sep 2022",
  },
  {
    image: "/icons/politics.png",
    title: "Close and historical ties to the government",
    description: "Lorem ipsum dolor sit amet, consectetur",
    chips: ["Politics", "Defense"],
    category: "politics",
    label: "published",
    author: "Maria Doe",
    time: "20 Sep 2022",
  },
];

export { ArticlesData };
